version: "3"
services:
  namenode:
    image: apache/hadoop:3
    container_name: namenode
    hostname: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./namenode:/hadoop/dfs/name
    networks:
      - hadoop-cluster
    command:
      

  datanode:
    image: apache/hadoop:3
    container_name: datanode
    networks:
      - hadoop-cluster
    volumes:
      - ./datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=myhadoop
      - "CORE_CONF_fs_defaultFS=hdfs://namenode:9000"

networks:
  hadoop-cluster:
    driver: bridge
